import 'package:jp_app/src/core/data/snack.dart';

List<Snack> snackList = [
  Snack(
    foodName: "Burger",
    foodDescription: "__Enter Description here__",
    category: ["Vegan"],
    foodPrice: 5.60,
    foodLikes: 100,
    foodRating: 4.5,
    foodImage: "assets/graphics/burger.png",
    foodFavourit: false,
  ),
  Snack(
    foodName: "Cupcake Cat",
    foodDescription: "__Enter Description here__",
    category: ["Sweet"],
    foodPrice: 2.50,
    foodLikes: 200,
    foodRating: 5.0,
    foodImage: "assets/graphics/cupcake_cat.png",
    foodFavourit: true,
  ),
  Snack(
    foodName: "Cupcake Chick",
    foodDescription: "__Enter Description here__",
    category: ["Sweet"],
    foodPrice: 1.50,
    foodLikes: 150,
    foodRating: 3.0,
    foodImage: "assets/graphics/cupcake_chick.png",
    foodFavourit: false,
  ),
  Snack(
    foodName: "Ice-Cream",
    foodDescription: "__Enter Description here__",
    category: ["Vegan", "Cold"],
    foodPrice: 5.60,
    foodLikes: 100,
    foodRating: 4.5,
    foodImage: "assets/graphics/icecream.png",
    foodFavourit: true,
  ),
  Snack(
    foodName: "Ice-Cream - Stick",
    foodDescription: "__Enter Description here__",
    category: ["Vegan", "Cold"],
    foodPrice: 5.60,
    foodLikes: 100,
    foodRating: 4.5,
    foodImage: "assets/graphics/icecream_stick.png",
    foodFavourit: false,
  ),
  Snack(
    foodName: "Ice-Cream - Cone",
    foodDescription: "__Enter Description here__",
    category: ["Vegan", "Cold"],
    foodPrice: 5.60,
    foodLikes: 100,
    foodRating: 4.5,
    foodImage: "assets/graphics/icecream_cone.png",
    foodFavourit: true,
  ),
];
